import {combineReducers} from 'redux';
import {
  // addEmployeeReducer,
  // getEmployeeReducer,
  // updateEmployeeReducer,
  userLoginReducer,
  userRegisterReducer,
} from './auth';
import {
  addBonusReducer,
  addClientReducer,
  addExpenceReducer,
  addHolidayReducer,
  addIncrementReducer,
  addOvertimeReducer,
  addProvidentReducer,
  addReferenceReducer,
  addSalarySReducer,
  deleteReducerReducer,
  editIncrementReducer,
  editProvidentReducer,
  getBonusReducer,
  getClientReducer,
  getExpenceReducer,
  getHolidayReducer,
  updateHolidayReducer,
  getIncrementReducer,
  getOvertimeReducer,
  getProvidentReducer,
  getReferenceReducer,
  getSalarySReducer,
  updateBonusReducer,
  updateClientReducer,
  updateEoReducer,
  updateExpReducer,
  updateSSReducer,
  deleteExpReducer,
  deleteEoReducer,
  deleteBonusReducer,
  addEmployeeReducer,
  getEmployeeReducer,
  updateEmployeeReducer,
  deleteSSReducer,
  deleteEmployeeReducer,
  deleteHolidayReducer,
  deleteProvidentReducer,
  deleteIncrementReducer,
  leaveReducer,
  getLeaveReucer,
  updateLeaveReducer,
  attandanceListReducer,
  inTimeReducer,
  outTimeReducer,
  profileReducer,
  singleAttandanceListReducer,
  getSingleOvertimeReducer,
  getSingleSalarySReducer,
  getSingleExpenceReducer,
  getSingleIncrementReducer,
  getSingleBonusReducer,
  getSingleProvidentReducer,
  getSingleLeaveReucer,
  getAdminReducer,
} from './main';

export default combineReducers({
  userLogin: userLoginReducer,
  userRegister: userRegisterReducer,
  //......|| EMPLOYEES ||.....
  addEmployee: addEmployeeReducer,
  getEmployee: getEmployeeReducer,
  updateEmployee: updateEmployeeReducer,
  deleteEmployee: deleteEmployeeReducer,
  //......|| CLIENTS ||.....
  addClient: addClientReducer,
  getClient: getClientReducer,
  deleteClient: deleteReducerReducer,
  updateClient: updateClientReducer,
  //......|| REFERENCE ||....
  addReference: addReferenceReducer,
  getReference: getReferenceReducer,
  //......|| EXPENCE ||......
  addExpence: addExpenceReducer,
  getExpence: getExpenceReducer,
  getSingleExpence: getSingleExpenceReducer,
  updateExp: updateExpReducer,
  deleteExp: deleteExpReducer,
  //......|| OVERTIME ||.......
  addOvertime: addOvertimeReducer,
  getOvertime: getOvertimeReducer,
  getSingleOvertime: getSingleOvertimeReducer,
  updateOverTime: updateEoReducer,
  deleteOverTime: deleteEoReducer,
  //......|| SALARY ||.........
  addSalary: addSalarySReducer,
  getSalary: getSalarySReducer,
  getSingleSalary: getSingleSalarySReducer,
  updateSalary: updateSSReducer,
  deleteSalary: deleteSSReducer,
  //......|| BONUS ||.......
  getBonus: getBonusReducer,
  getSingleBonus: getSingleBonusReducer,
  addBonus: addBonusReducer,
  updateBonus: updateBonusReducer,
  deleteBonus: deleteBonusReducer,
  //......|| PROVIDENT ||.......
  addProvident: addProvidentReducer,
  getProvident: getProvidentReducer,
  getSingleProvident: getSingleProvidentReducer,
  editProvident: editProvidentReducer,
  deleteProvident: deleteProvidentReducer,
  //......|| HOLIDAY ||........
  addHoliday: addHolidayReducer,
  getHoliday: getHolidayReducer,
  updateHoliday: updateHolidayReducer,
  deleteHoliday: deleteHolidayReducer,
  //......|| INCREMENT ||....
  addIncrement: addIncrementReducer,
  getIncrement: getIncrementReducer,
  getSingleIncrement: getSingleIncrementReducer,
  editIncrement: editIncrementReducer,
  deleteIncrement: deleteIncrementReducer,
  //......|| LEAVE MANAGMENET ||.......
  leaveSend: leaveReducer,
  getLeave: getLeaveReucer,
  getSingleLeave: getSingleLeaveReucer,
  updateLeave: updateLeaveReducer,
  //......|| ATTANDANCE LIST ||........
  attandanceList: attandanceListReducer,
  attandanceIntime: inTimeReducer,
  attandanceOuttime: outTimeReducer,
  sinleAttandanceList: singleAttandanceListReducer,
  //...... || PROFILE IMAGE ||......
  profileImage: profileReducer,
  //.......|| GET ADMIN ||.......
  getAdmin: getAdminReducer,
});
