export const CREATE_JOINROOM_REQUEST = 'CREATE_JOINROOM_REQUEST';
export const CREATE_JOINROOM_SUCCESS = 'CREATE_JOINROOM_SUCCESS';
export const CREATE_JOINROOM_FAIL = 'CREATE_JOINROOM_FAIL';
//GET
export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAIL = 'GET_ROOMS_FAIL';
//DELETE
export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';
