//..............|| ADD CLIENT CONSTANTS ||......
export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';
//..............|| GET CLIENT CONSTANTS ||........
export const GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAIL = 'GET_CLIENT_FAIL';
//..............|| DELETE CLIENT CONSTANTS ||........
export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';
//..............|| UPDATE CLIENT CONSTANTS ||........
export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL';
//..............|| ADD REFERENCE CONSTANTS ||........
export const ADD_REFERENCE_REQUEST = 'ADD_REFERENCE_REQUEST';
export const ADD_REFERENCE_SUCCESS = 'ADD_REFERENCE_SUCCESS';
export const ADD_REFERENCE_FAIL = 'ADD_REFERENCE_FAIL';
//..............|| GET REFERENCE CONSTANTS ||........
export const GET_REFERENCE_REQUEST = 'GET_REFERENCE_REQUEST';
export const GET_REFERENCE_SUCCESS = 'GET_REFERENCE_SUCCESS';
export const GET_REFERENCE_FAIL = 'GET_REFERENCE_FAIL';
//..............|| ADD EXPENCE CONSTANTS ||..........
export const ADD_EXPENCE_REQUEST = 'ADD_EXPENCE_REQUEST';
export const ADD_EXPENCE_SUCCESS = 'ADD_EXPENCE_SUCCESS';
export const ADD_EXPENCE_FAIL = 'ADD_EXPENCE_FAIL';
//..............|| GET EXPENCE CONSTANTS ||..........
export const GET_EXPENCE_REQUEST = 'GET_EXPENCE_REQUEST';
export const GET_EXPENCE_SUCCESS = 'GET_EXPENCE_SUCCESS';
export const GET_EXPENCE_FAIL = 'GET_EXPENCE_FAIL';
//..............|| GET SINGLE EXPENCE CONSTANTS ||..........
export const GET_SINGLE_EXPENCE_REQUEST = 'GET_SINGLE_EXPENCE_REQUEST';
export const GET_SINGLE_EXPENCE_SUCCESS = 'GET_SINGLE_EXPENCE_SUCCESS';
export const GET_SINGLE_EXPENCE_FAIL = 'GET_SINGLE_EXPENCE_FAIL';
//..............|| update EXPENCE CONSTANTS ||..........
export const UPDATE_EXPENCE_REQUEST = 'UPDATE_EXPENCE_REQUEST';
export const UPDATE_EXPENCE_SUCCESS = 'UPDATE_EXPENCE_SUCCESS';
export const UPDATE_EXPENCE_FAIL = 'UPDATE_EXPENCE_FAIL';
//..............|| DELETE EXPENCE CONSTANTS ||..........
export const DELETE_EXPENCE_REQUEST = 'DELETE_EXPENCE_REQUEST';
export const DELETE_EXPENCE_SUCCESS = 'DELETE_EXPENCE_SUCCESS';
export const DELETE_EXPENCE_FAIL = 'DELETE_EXPENCE_FAIL';
//..............|| ADD OVERTIME CONSTANTS ||.........
export const ADD_OVERTIME_REQUEST = 'ADD_OVERTIME_REQUEST';
export const ADD_OVERTIME_SUCCESS = 'ADD_OVERTIME_SUCCESS';
export const ADD_OVERTIME_FAIL = 'ADD_OVERTIME_FAIL';
//..............|| GET OVERTIME CONSTANTS ||.........
export const GET_OVERTIME_REQUEST = 'GET_OVERTIME_REQUEST';
export const GET_OVERTIME_SUCCESS = 'GET_OVERTIME_SUCCESS';
export const GET_OVERTIME_FAIL = 'GET_OVERTIME_FAIL';
//..............|| GET SINGLE OVERTIME CONSTANTS BY ID ||.........
export const GET_SINGLE_OVERTIME_REQUEST = 'GET_SINGLE_OVERTIME_REQUEST';
export const GET_SINGLE_OVERTIME_SUCCESS = 'GET_SINGLE_OVERTIME_SUCCESS';
export const GET_SINGLE_OVERTIME_FAIL = 'GET_SINGLE_OVERTIME_FAIL';
//..............|| UPDATE OVERTIME CONSTANTS ||.........
export const UPDATE_OVERTIME_REQUEST = 'UPDATE_OVERTIME_REQUEST';
export const UPDATE_OVERTIME_SUCCESS = 'UPDATE_OVERTIME_SUCCESS';
export const UPDATE_OVERTIME_FAIL = 'UPDATE_OVERTIME_FAIL';
//..............|| DELETE OVERTIME CONSTANTS ||.........
export const DELETE_OVERTIME_REQUEST = 'DELETE_OVERTIME_REQUEST';
export const DELETE_OVERTIME_SUCCESS = 'DELETE_OVERTIME_SUCCESS';
export const DELETE_OVERTIME_FAIL = 'DELETE_OVERTIME_FAIL';
//..............|| ADD SALARY STATEMENT CONSTANTS ||.....
export const ADD_SALARYSTATEMENT_REQUEST = 'ADD_SALARYSTATEMENT_REQUEST';
export const ADD_SALARYSTATEMENT_SUCCESS = 'ADD_SALARYSTATEMENT_SUCCESS';
export const ADD_SALARYSTATEMENT_FAIL = 'ADD_SALARYSTATEMENT_FAIL';
//..............|| GET SALARY STATEMENT CONSTANTS ||.....
export const GET_SALARYSTATEMENT_REQUEST = 'GET_SALARYSTATEMENT_REQUEST';
export const GET_SALARYSTATEMENT_SUCCESS = 'GET_SALARYSTATEMENT_SUCCESS';
export const GET_SALARYSTATEMENT_FAIL = 'GET_SALARYSTATEMENT_FAIL';
//..............|| GET SINGLE SALARY STATEMENT CONSTANTS ||.....
export const GET_SINGLE_SALARYSTATEMENT_REQUEST =
  'GET_SINGLE_SALARYSTATEMENT_REQUEST';
export const GET_SINGLE_SALARYSTATEMENT_SUCCESS =
  'GET_SINGLE_SALARYSTATEMENT_SUCCESS';
export const GET_SINGLE_SALARYSTATEMENT_FAIL =
  'GET_SINGLE_SALARYSTATEMENT_FAIL';
//..............|| UPDATE SALARY STATEMENT CONSTANTS ||.....
export const UPDATE_SALARYSTATEMENT_REQUEST = 'UPDATE_SALARYSTATEMENT_REQUEST';
export const UPDATE_SALARYSTATEMENT_SUCCESS = 'UPDATE_SALARYSTATEMENT_SUCCESS';
export const UPDATE_SALARYSTATEMENT_FAIL = 'UPDATE_SALARYSTATEMENT_FAIL';
//..............|| DELETE SALARY STATEMENT CONSTANTS ||.....
export const DELETE_SALARYSTATEMENT_REQUEST = 'DELETE_SALARYSTATEMENT_REQUEST';
export const DELETE_SALARYSTATEMENT_SUCCESS = 'DELETE_SALARYSTATEMENT_SUCCESS';
export const DELETE_SALARYSTATEMENT_FAIL = 'DELETE_SALARYSTATEMENT_FAIL';
//..............|| GET BONUS CONSTANTS ||.........
export const GET_BONUS_REQUEST = 'GET_BONUS_REQUEST';
export const GET_BONUS_SUCCESS = 'GET_BONUS_SUCCESS';
export const GET_BONUS_FAIL = 'GET_BONUS_FAIL';
//..............|| GET SINGLE  BONUS CONSTANTS ||.........
export const GET_SINGLE_BONUS_REQUEST = 'GET_SINGLE_BONUS_REQUEST';
export const GET_SINGLE_BONUS_SUCCESS = 'GET_SINGLE_BONUS_SUCCESS';
export const GET_SINGLE_BONUS_FAIL = 'GET_SINGLE_BONUS_FAIL';
//..............|| ADD BONUS CONSTANTS ||.........
export const ADD_BONUS_REQUEST = 'ADD_BONUS_REQUEST';
export const ADD_BONUS_SUCCESS = 'ADD_BONUS_SUCCESS';
export const ADD_BONUS_FAIL = 'ADD_BONUS_FAIL';
//..............|| UPDATE BONUS CONSTANTS ||.........
export const UPDATE_BONUS_REQUEST = 'UPDATE_BONUS_REQUEST';
export const UPDATE_BONUS_SUCCESS = 'UPDATE_BONUS_SUCCESS';
export const UPDATE_BONUS_FAIL = 'UPDATE_BONUS_FAIL';
//..............|| DELETE BONUS CONSTANTS ||.........
export const DELETE_BONUS_REQUEST = 'DELETE_BONUS_REQUEST';
export const DELETE_BONUS_SUCCESS = 'DELETE_BONUS_SUCCESS';
export const DELETE_BONUS_FAIL = 'DELETE_BONUS_FAIL';
//..............|| ADD HOLIDAY CONSTANTS ||.........
export const ADD_HOLIDAY_REQUEST = 'ADD_HOLIDAY_REQUEST';
export const ADD_HOLIDAY_SUCCESS = 'ADD_HOLIDAY_SUCCESS';
export const ADD_HOLIDAY_FAIL = 'ADD_HOLIDAY_FAIL';
//..............|| GET HOLIDAY CONSTANTS ||.........
export const GET_HOLIDAY_REQUEST = 'GET_HOLIDAY_REQUEST';
export const GET_HOLIDAY_SUCCESS = 'GET_HOLIDAY_SUCCESS';
export const GET_HOLIDAY_FAIL = 'GET_HOLIDAY_FAIL';
//..............|| UDATE HOLIDAY CONSTANTS ||.........
export const UPDATE_HOLIDAY_REQUEST = 'UPDATE_HOLIDAY_REQUEST';
export const UPDATE_HOLIDAY_SUCCESS = 'UPDATE_HOLIDAY_SUCCESS';
export const UPDATE_HOLIDAY_FAIL = 'UPDATE_HOLIDAY_FAIL';
//..............|| DELETE HOLIDAY CONSTANTS ||.........
export const DELETE_HOLIDAY_REQUEST = 'DELETE_HOLIDAY_REQUEST';
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_FAIL = 'DELETE_HOLIDAY_FAIL';
//..............|| ADD PROVIDENT FUND CONSTANTS ||.........
export const ADD_PROVIDENT_REQUEST = 'ADD_PROVIDENT_REQUEST';
export const ADD_PROVIDENT_SUCCESS = 'ADD_PROVIDENT_SUCCESS';
export const ADD_PROVIDENT_FAIL = 'ADD_PROVIDENT_FAIL';
//..............|| GET PROVIDENT FUND CONSTANTS ||.........
export const GET_PROVIDENT_REQUEST = 'GET_PROVIDENT_REQUEST';
export const GET_PROVIDENT_SUCCESS = 'GET_PROVIDENT_SUCCESS';
export const GET_PROVIDENT_FAIL = 'GET_PROVIDENT_FAIL';
//..............|| GET SINGLE PROVIDENT FUND CONSTANTS ||.........
export const GET_SINGLE_PROVIDENT_REQUEST = 'GET_SINGLE_PROVIDENT_REQUEST';
export const GET_SINGLE_PROVIDENT_SUCCESS = 'GET_SINGLE_PROVIDENT_SUCCESS';
export const GET_SINGLE_PROVIDENT_FAIL = 'GET_SINGLE_PROVIDENT_FAIL';
//..............|| UPDATE PROVIDENT FUND CONSTANTS ||.........
export const UPDATE_PROVIDENT_REQUEST = 'UPDATE_PROVIDENT_REQUEST';
export const UPDATE_PROVIDENT_SUCCESS = 'UPDATE_PROVIDENT_SUCCESS';
export const UPDATE_PROVIDENT_FAIL = 'UPDATE_PROVIDENT_FAIL';
//..............|| DELETE PROVIDENT FUND CONSTANTS ||.........
export const DELETE_PROVIDENT_REQUEST = 'DELETE_PROVIDENT_REQUEST';
export const DELETE_PROVIDENT_SUCCESS = 'DELETE_PROVIDENT_SUCCESS';
export const DELETE_PROVIDENT_FAIL = 'DELETE_PROVIDENT_FAIL';
//..............|| ADD INCREMENT LIST ||............
export const ADD_INCREMENTLIST_REQUEST = 'ADD_INCREMENTLIST_REQUEST';
export const ADD_INCREMENTLIST_SUCCESS = 'ADD_INCREMENTLIST_SUCCESS';
export const ADD_INCREMENTLIST_FAIL = 'ADD_INCREMENTLIST_FAIL';
//..............|| GET INCREMENT LIST ||............
export const GET_INCREMENTLIST_REQUEST = 'GET_INCREMENTLIST_REQUEST';
export const GET_INCREMENTLIST_SUCCESS = 'GET_INCREMENTLIST_SUCCESS';
export const GET_INCREMENTLIST_FAIL = 'GET_INCREMENTLIST_FAIL';
//..............|| GET SINGLE INCREMENT LIST ||............
export const GET_SINGLE_INCREMENTLIST_REQUEST =
  'GET_SINGLE_INCREMENTLIST_REQUEST';
export const GET_SINGLE_INCREMENTLIST_SUCCESS =
  'GET_SINGLE_INCREMENTLIST_SUCCESS';
export const GET_SINGLE_INCREMENTLIST_FAIL = 'GET_SINGLE_INCREMENTLIST_FAIL';
//..............|| UPDATE INCREMENT LIST ||............
export const UPDATE_INCREMENTLIST_REQUEST = 'UPDATE_INCREMENTLIST_REQUEST';
export const UPDATE_INCREMENTLIST_SUCCESS = 'UPDATE_INCREMENTLIST_SUCCESS';
export const UPDATE_INCREMENTLIST_FAIL = 'UPDATE_INCREMENTLIST_FAIL';
//..............|| DELETE INCREMENT LIST ||............
export const DELETE_INCREMENTLIST_REQUEST = 'DELETE_INCREMENTLIST_REQUEST';
export const DELETE_INCREMENTLIST_SUCCESS = 'DELETE_INCREMENTLIST_SUCCESS';
export const DELETE_INCREMENTLIST_FAIL = 'DELETE_INCREMENTLIST_FAIL';

//...................|| ADD EMPLOYEE CONSTANTS WITH DETAILS ||..........
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL';

//..................|| GET EMPLOYEE CONSTANTS WITH DETAILS ||...........
export const GET_EMPLOYEE_REQUEST = 'GET_EMPLOYEE_REQUEST';
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAIL = 'GET_EMPLOYEE_FAIL';

//..................|| UPDATE EMPLOYEE CONSTANTS WITH DETAILS ||........
export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL';

//..............|| DELETE EMPLOYEE CONSTANTS ||.........
export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL';
//..............|| LEAVE MANAGMENT CONSTANTS ||.........
export const LEAVE_REQUEST = 'LEAVE_REQUEST';
export const LEAVE_SUCCESS = 'LEAVE_SUCCESS';
export const LEAVE_FAIL = 'LEAVE_FAIL';
//..............|| GET MANAGMENT CONSTANTS ||.........
export const GET_LEAVE_REQUEST = 'GET_LEAVE_REQUEST';
export const GET_LEAVE_SUCCESS = 'GET_LEAVE_SUCCESS';
export const GET_LEAVE_FAIL = 'GET_LEAVE_FAIL';
//..............|| GET SINGLE MANAGMENT CONSTANTS ||.........
export const GET_SINGLE_LEAVE_REQUEST = 'GET_SINGLE_LEAVE_REQUEST';
export const GET_SINGLE_LEAVE_SUCCESS = 'GET_SINGLE_LEAVE_SUCCESS';
export const GET_SINGLE_LEAVE_FAIL = 'GET_SINGLE_LEAVE_FAIL';
//..............|| UPDATE LEAVE APPLICATION CONSTANTS ||........
export const UPDATE_LEAVE_REQUEST = 'UPDATE_LEAVE_REQUEST';
export const UPDATE_LEAVE_SUCCESS = 'UPDATE_LEAVE_SUCCESS';
export const UPDATE_LEAVE_FAIL = 'UPDATE_LEAVE_FAIL';
//.............. || ATTANDANCE IN TIME CONSTANTS ||..........
export const ATTANDANCE_INTIME_REQUEST = 'ATTANDANCE_INTIME_REQUEST';
export const ATTANDANCE_INTIME_SUCCESS = 'ATTANDANCE_INTIME_SUCCESS';
export const ATTANDANCE_INTIME_FAIL = 'ATTANDANCE_INTIME_FAIL';
//.............. || ATTANDANCE OUR TIME CONSTANTS ||..........
export const ATTANDANCE_OUTTIME_REQUEST = 'ATTANDANCE_OUTTIME_REQUEST';
export const ATTANDANCE_OUTTIME_SUCCESS = 'ATTANDANCE_OUTTIME_SUCCESS';
export const ATTANDANCE_OUTTIME_FAIL = 'ATTANDANCE_OUTTIME_FAIL';
//.............. || ATTANDANCE LIST CONSTANTS ||..........
export const ATTANDANCE_LIST_REQUEST = 'ATTANDANCE_LIST_REQUEST';
export const ATTANDANCE_LIST_SUCCESS = 'ATTANDANCE_LIST_SUCCESS';
export const ATTANDANCE_LIST_FAIL = 'ATTANDANCE_LIST_FAIL';
//.............. || SINGLE employee LIST CONSTANTS ||..........
export const SINGLE_EMPLOYEE_LIST_REQUEST = 'SINGLE_EMPLOYEE_LIST_REQUEST';
export const SINGLE_EMPLOYEE_LIST_SUCCESS = 'SINGLE_EMPLOYEE_LIST_SUCCESS';
export const SINGLE_EMPLOYEE_LIST_FAIL = 'SINGLE_EMPLOYEE_LIST_FAIL';
//.............. || SINGLE ATTANDANCE LIST CONSTANTS ||..........
export const ATTANDANCE_LIST_REQUEST_SINGLE = 'ATTANDANCE_LIST_REQUEST_SINGLE';
export const ATTANDANCE_LIST_SUCCESS_SINGLE = 'ATTANDANCE_LIST_SUCCESS_SINGLE';
export const ATTANDANCE_LIST_FAIL_SINGLE = 'ATTANDANCE_LIST_FAIL_SINGLE';
//...............|| PROFILE IMAGE CONTSTANTS ||............
export const PROFILE_IMAGE_REQUEST = 'PROFILE_IMAGE_REQUEST';
export const PROFILE_IMAGE_SUCCESS = 'PROFILE_IMAGE_SUCCESS';
export const PROFILE_IMAGE_FAIL = 'PROFILE_IMAGE_FAIL';
//...............|| ADMIN CONTSTANTS ||............
export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAIL = 'GET_ADMIN_FAIL';
